### ISSUE TITLE
Unable to alter selection in ComboTreeBoxCell if column's UseNodeNamesForPath is set to true

### ISSUE THREAD

**Issue by ROSeaboyer** [BradSmith1985/DropDownControls#2]
If I have UseNodeNamesForPath set to true, I'm unable to edit any ComboTreeBoxCell values.

The issue appears to be within the InitializeEditingControl function within ComboTreeBoxCell, but I'm unable to figure out where exactly yet.

**Comment by BradSmith1985** [comment]
Was able to reproduce the problem. The value of `UseNodeNamesForPath` was not being applied to the editing control. This is fixed in the latest commit. Thanks for identifying this issue!
